name: KathoUtils
description: A Plugin to make some good things like register, login, map and help the my private servers.
author: Katho
version: 1.0.0
main: io.katho.utils.KathoUtils
commands:
   register:
      description: You can register yourself using this command.
      aliases: [registrar]
   login:
      description: You log in yourself using this command.
      aliases: [entrar]