name: KathoCore
description: Just the best utils plugin.
author: Katho
version: 1.0.0
main: io.katho.core.Core
commands:
   register:
      description: You can register yourself using this command.
      aliases: [registrar]
   login:
      description: You log in yourself using this command.
      aliases: [entrar]
